### ISSUE TITLE
no matched organism in chado.organism

### ISSUE THREAD

**Issue by elor77** [UofS-Pulse-Binfo/tripal_germplasm_importer#21]
Hi Lacey

We're in the proccess of learning these tools so we went ahead and created a sample site based on TRIPAL tutorial. We've succesfully installed some modules. Now we want to upload our germplasm file. 
When trying to upload my germplasm file I get the following error 
`ERROR: The genus, Citrus, species, sinensis, has no matched organism in chado.organism.`

I already created this organism  and veryfied it's existence in the db (chado.organism table) so I'm not sure what this error means
Thanks 
Elad

**Comment by laceysanderson** [comment]
Hi @elor77,

This error is [very specific](https://github.com/UofS-Pulse-Binfo/tripal_germplasm_importer/blob/7d4c582be9ceabb44951e89b3a5c9b2e65ea4c60/includes/TripalImporter/GermplasmAccessionImporter.inc#L342-L365) and should only happen if the matching organism is not in the table which is not the case for you. 

Can you provide the file so we can see exactly what is going on?

**Comment by elor77** [comment]
@laceysanderson here's our germplasm file:
[tadxdul_germplasm.txt](https://github.com/UofS-Pulse-Binfo/tripal_germplasm_importer/files/4339654/tadxdul_germplasm.txt)

**Comment by laceysanderson** [comment]
Oh interesting, it appears the first two records in your file have an infraspecific name:
```
TAMDEW	ARO-NY	TAMDEW	Citrus	sinensis	inodorus	NY-IL	Neve_Yaar	USA	400	conventional	TAD (TADA-195-2-1-B-B)	
DULCE	ARO-NY	DULCE	Citrus	sinensis	reticulatus	NY-IL	Neve_Yaar	ISL	400	conventional	DUL (DUL-B-10-293-B-B-B-B-B)	
```

Specifically, `Citrus sinensis inodorus` and `Citrus sinensis reticulatus`, whereas, the rest of the accessions do not have an infraspecific name. Note that if you remove those two infraspecific names (needed due to bug #22) and add the database (`ARO-NY` using form `admin/tripal/loaders/chado_db/add`) that file loads perfectly 👍

**Comment by elor77** [comment]
@laceysanderson 
Success!! 
Prayers for good health by all...
